### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [trackify-info/GoogleTagManager-WebTemplate-Tawkto#1]
https://github.com/trackify-info/GoogleTagManager-WebTemplate-Tawkto/blob/9003e57af562d10883ff5c61141449408e48b1bb/template.tpl#L82

We've noticed that your template is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by SOFTWORK** [comment]
it should be fixed
